# Base image
FROM node:latest

RUN mkdir /usr/src/frontend

# Set working directory
WORKDIR /usr/src/frontend

COPY ./frontend/package.json ./package.json

RUN ls -la

# Install dependencies
# RUN ls -al
RUN npm install

# Copy app code
COPY ./frontend .

# Start app with HMR
CMD ["npm", "start"]