version: '3'

services:
  # Backend service using Laravel
  backend:
    container_name: feelit-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    environment:
      DB_HOST: http://localhost
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - app-network

  # Frontend service using React
  # frontend:
  #   container_name: feelit-frontend
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   networks:
  #     - app-network

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: feelit-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db
      - backend

  # Database service using MySQL
  db:
    image: mysql:latest
    container_name: feelit-mysql-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge