# Base image
FROM php:8.1-fpm

# Set working directory
WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
        git \
        unzip \
        libzip-dev \
        libonig-dev \
        libxml2-dev && \
    docker-php-ext-install pdo_mysql zip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy app code
COPY . .

# Install dependencies with Composer
RUN composer install

# Copy environment variables
COPY .env.example .env

# Generate application key
RUN php artisan key:generate

# Run database migrations and seeding
RUN php artisan migrate:fresh --seed

# Start development server
CMD ["php", "artisan", "serve", "--host", "0.0.0.0"]