# Base image
FROM php:8.1-fpm

RUN mkdir /usr/src/backend

# Set working directory
WORKDIR /usr/src/backend

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
        git \
        unzip \
        libzip-dev \
        libonig-dev \
        libxml2-dev && \
    docker-php-ext-install pdo_mysql zip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy app code
COPY ./backend .

# Install dependencies with Composer
RUN composer install

# Copy environment variables
COPY ./backend/.env.example .env

# Generate application key
RUN php artisan key:generate

# Optimizing Configuration loading
RUN php artisan config:clear

# Optimizing Route loading
RUN php artisan cache:clear

# Run database migrations and seeding
# RUN php artisan migrate:fresh --seed

# Start development server
# CMD ["php", "artisan", "serve", "--host", "0.0.0.0"]

copy ./run.sh /tmp

# # Run database migrations and seeding
ENTRYPOINT ["timeout", "10000", "/tmp/run.sh"]